-- GeoNames ZA postal codes (free dataset)
-- Source: https://download.geonames.org/export/zip/ (ZA.zip)
-- Format reference: https://download.geonames.org/export/zip/readme.txt
--
-- Goal: Provide a free, reliable postal-code lookup without calling GeoNames webservices.
-- The mobile app will query via RPC `search_za_postal_codes`.

create table if not exists public.za_postal_codes (
  id bigint generated by default as identity primary key,
  country_code text not null default 'ZA',
  postal_code text not null,
  place_name text null,
  admin_name1 text null,
  admin_name2 text null,
  admin_name3 text null,
  latitude double precision null,
  longitude double precision null,
  accuracy integer null,
  created_at timestamptz not null default now()
);

comment on table public.za_postal_codes is
  'GeoNames postal-code dump subset for South Africa (ZA). Loaded from ZA.txt (tab-delimited).';

create index if not exists za_postal_codes_postal_code_idx
  on public.za_postal_codes (postal_code);

create index if not exists za_postal_codes_place_name_idx
  on public.za_postal_codes (place_name);

create index if not exists za_postal_codes_admin_name2_idx
  on public.za_postal_codes (admin_name2);

alter table public.za_postal_codes enable row level security;

-- Public read is OK: this table contains no private user data.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'za_postal_codes'
      and policyname = 'Public read postal codes'
  ) then
    create policy "Public read postal codes"
      on public.za_postal_codes
      for select
      using (true);
  end if;
end $$;

-- Search RPC: returns distinct postal codes for a query.
-- This mimics GeoNames "placename" behavior (searches across place + admin fields).
-- Parameter order (p_limit, p_query) matches PostgREST schema cache lookup.
create or replace function public.search_za_postal_codes(
  p_limit integer default 500,
  p_query text default ''
)
returns table (postal_code text)
language sql
stable
as $$
  select distinct z.postal_code
  from public.za_postal_codes z
  where
    z.country_code = 'ZA'
    and (
      z.postal_code ilike '%' || p_query || '%'
      or z.place_name ilike '%' || p_query || '%'
      or z.admin_name2 ilike '%' || p_query || '%'
      or z.admin_name3 ilike '%' || p_query || '%'
    )
  order by z.postal_code
  limit least(greatest(p_limit, 1), 2000);
$$;

grant execute on function public.search_za_postal_codes(integer, text) to anon, authenticated;

-- Get distinct provinces (admin_name1) for signup/forms
create or replace function public.get_za_provinces()
returns table (name text)
language sql
stable
as $$
  select distinct admin_name1 as name
  from public.za_postal_codes
  where country_code = 'ZA' and admin_name1 is not null and admin_name1 != ''
  order by admin_name1;
$$;

-- Get distinct cities (place_name) for a province
create or replace function public.get_za_cities_by_province(p_province text)
returns table (name text)
language sql
stable
as $$
  select distinct place_name as name
  from public.za_postal_codes
  where country_code = 'ZA'
    and admin_name1 = p_province
    and place_name is not null
    and place_name != ''
  order by place_name;
$$;

grant execute on function public.get_za_provinces() to anon, authenticated;
grant execute on function public.get_za_cities_by_province(text) to anon, authenticated;

